### ISSUE TITLE
Could not resolve Jamepad dependencies

### ISSUE THREAD

**Issue by aberkowski** [MrStahlfelge/gdx-controllerutils#11]
Hi, I want to use Jamepad controller implementation but I get error after adding this line to build.gradle: compile "de.golfgl.gdxcontrollerutils:gdx-controllers-jamepad:$cuversion":

Error:Gradle: Could not resolve all dependencies for configuration ':desktop:compileClasspath'.
> Could not find com.github.WilliamAHartman:Jamepad:1.2.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.pom
      https://repo1.maven.org/maven2/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.jar
      https://oss.sonatype.org/content/repositories/snapshots/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.pom
      https://oss.sonatype.org/content/repositories/snapshots/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.jar
      https://oss.sonatype.org/content/repositories/releases/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.pom
      https://oss.sonatype.org/content/repositories/releases/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.jar
      https://maven.google.com/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.pom
      https://maven.google.com/com/github/WilliamAHartman/Jamepad/1.2/Jamepad-1.2.jar
  Required by:
      project :desktop > de.golfgl.gdxcontrollerutils:gdx-controllers-jamepad:0.3.0

What am I doing wrong?

**Comment by MrStahlfelge** [comment]
Probably you need to add Jitpack like explained here: https://github.com/williamahartman/Jamepad#using-jamepad

Does this solve it? I'll add it to the documentation here.

**Comment by aberkowski** [comment]
Yes, now it works. Thanks!
