### ISSUE TITLE
Funky interactions with SelectBox lists

### ISSUE THREAD

**Issue by Fenekhu** [MrStahlfelge/gdx-controllerutils#19]
I'm making a game that's meant to be played only with a controller (or keyboard) and I'm currently working on the options screen. The problem is that when I open the SelectBox the input goes to the other buttons first, and only scrolls through the list once I get to the top/bottom of the options behind it. If I try to choose an option, it just activates the other selected button instead of choosing an option.

**Comment by MrStahlfelge** [comment]
Hi, based on the discussion on Reddit I think you already came up with a solution?

**Comment by MrStahlfelge** [comment]
No reaction
