### ISSUE TITLE
setFocusedActor(null) does not work, only returns false, can't unset the current focused actor

### ISSUE THREAD

**Issue by Azania** [MrStahlfelge/gdx-controllerutils#24]
ControllerMenuStage#setFocusedActor(Actor actor) on line 140/141:
..
if (actor == null || !isActorFocusable(actor))
    return false;
..

This causes unable to set the current focused actor to null. Based on the ControllerMenuStage#unfocus(Actor actor) and unfocusAll() this is supposed to be possible as they also set setFocusedActor(null); but this isn't possible as it just returns false without setting it to null. This is most prevalent with onControllerDefaultKeyUp from the IControllerActable interface which will still work even after clearFocusableActors(); meaning you can keep on spamming the button without any way to stop it.

**Comment by MrStahlfelge** [comment]
Thank you for the hint, that's a bug.

**Comment by MrStahlfelge** [comment]
Please check if 2.2.1-SNAPSHOT fits your needs

**Comment by Azania** [comment]
Yup seems good now, I can only see the source here on git hub and not in my IDE but I assume it is the same. Also my code is now working back to how it should be without spamming on the button being possible :P So thank you!

Also thank you for making the comment in english, as you seen in my post edit history yeah I was wondering about it while the if was there but through a roundabout way with focus cancel calling a listener that could change the focusedActor then yeah the if is needed.
